image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose up -d
  - java -jar artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true